# Generated by Django 3.2.7 on 2021-09-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-created',)},
        ),
    ]
